# Generated by Django 3.2.8 on 2021-12-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_client',
        ),
    ]
